image: node:18.1.0-alpine3.15

stages:
  - build 

.build:
  artifacts: &build_artifacts
    name: $artifact_name
    paths:
      - $artifact_name
  script: &build_script
    - cd WebApplicationClient~
    - yarn install
    - yarn run deploy
    - cd ..
    - mkdir -p ${artifact_name}
    - cp WebApplicationClient~/SWInspector-StreamingAssets.zip ${artifact_name}/

build:
  stage: build
  except:
    - tags
  variables:
    artifact_name: dev.r01.simplewebinspector-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  artifacts: *build_artifacts
  script: *build_script

build_for_release:
  stage: build
  only:
    - tags
  variables:
    artifact_name: dev.r01.simplewebinspector-${CI_COMMIT_TAG}
  artifacts: *build_artifacts
  script: *build_script
